[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-sandbox",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libatspi2.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxkbcommon0",
  "libxrandr2",
  "xdg-utils"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node server.js"
